#testing
- id: 10.1242/jeb.249548
  image: https://cob.silverchair-cdn.com/cob/content_public/journal/jeb/228/11/10.1242_jeb.249548/1/jeb24954803.png?Expires=1758205429&Signature=nBUClhBiSnEOtZpuRN-0Tjg0N1azfyk18Y9FF8n1Nsz4as7ZQRcTVoWEoWJ8LjwJNzdl~okIyJm5RFoLuHRwC54IwubofXnVTfpkagkPPVp4nNK3~4Z~~mHUUoXFu7DsHMiYoHhsq6i3zG0KI2xxA-EiFyk0vXEi0QfAKCbyRf80JdGVV7RvH66uV9SQ1EbLdFHNKCoJxY5AfI0i~yV5DMhMeFLXltg-gSrF6tMSU7Ukvs3Av48uZTO0gYTFH74HM1UmK5ru3tF~wOyuSbljJegXtlLjU0bD5X4MD6mGrSaamVAB4Ny54~O0zwqCjsM5VydCPt7hInkD5foH69NdSg__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags:
    - Transcriptome
    - Reproduction
    - Signal Evolution

- id: 10.1002/jez.b.23242
  image: https://onlinelibrary.wiley.com/cms/asset/96032b62-2449-419b-ad26-9a4f7bcb0edf/jezb23242-fig-0001-m.jpg
  tags:
      - Reproduction

- id: 10.1016/j.cub.2023.11.062
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0960982223016500-fx1.jpg
  tags:
    - Transcriptome

- id: doi:10.1093/g3journal/jkac331
  image: images/epdltree.png
  tags:
    - Signal Evolution
    - Genome

- id: doi:10.1126/sciadv.abm2970
  image: images/bgaud_cover1_candidate.jpg
  tags:
      - Evo-Devo
  extra-links:
    - type: pdf
      link: images/sciadv.abm2970.pdf

- id: doi:10.1007/978-3-030-29105-1_4
  image: images/evodevo.png
  tags:
      - Evo-Devo
  extra-links:
    - type: pdf
      link: images/Gallant2019_Chapter_TheEvolutionAndDevelopmentOfEl.pdf

- id: doi:10.1111/jfb.14779
  image: https://onlinelibrary.wiley.com/cms/asset/192098fe-d44b-4a9c-a69c-e870233af510/jfb14779-fig-0001-m.jpg
  tags:
      - Reproduction
  extra-links:
    - type: pdf
      link: images/koenigandgallant2021.pdf

- id: doi:10.1111/evo.13953
  image: https://onlinelibrary.wiley.com/cms/asset/24de0b40-6882-44e7-8598-676ce326907d/evo13953-fig-0001-m.jpg
  tags:
      - Signal Evolution
  extra-links:
    - type: pdf
      link: images/picqetal2020.pdf

- id: doi:10.1242/jeb.213447
  image: images/m_jeb21344701.png
  tags:
      - Review
  extra-links:
    - type: pdf
      link: images/gallant_and_oconnell_2020.pdf

- id: doi:10.1186/s12862-019-1572-3
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs12862-019-1572-3/MediaObjects/12862_2019_1572_Fig2_HTML.png?as=webp
  tags:
      - Transcriptome
      - Signal Evolution
  extra-links:
    - type: pdf
      link: images/losilla_et_al_2020.pdf

- id: doi:10.1016/j.cub.2018.05.012
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0960982218306146-fx1.jpg
  tags:
    - Signal Evolution
  extra-links:
    - type: pdf
      link: images/immani_et_al_2019.pdf

- id: doi:10.3791/60253
  image: https://cloudfront.jove.com/files/ftp_upload/60253/60253fig06.jpg
  tags:
      - CRISPR
      - Protocol
  extra-links:
    - type: pdf
      link: images/constantinou_etal_2019.pdf

- id: doi:10.1093/gbe/evx265
  image: images/m_evx265f1.jpeg
  tags:
      - Genome
  extra-links:
    - type: pdf
      link: images/gallant_et_al_2017.pdf

- id: doi:10.1016/j.jphysparis.2016.10.003
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0928425716300079-gr1.jpg
  tags:
      - Review
  extra-links:
    - type: pdf
      link: images/pitchers_et_al_2016.pdf

- id: doi:10.1186/s12864-015-1288-8
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs12864-015-1288-8/MediaObjects/12864_2015_1288_Fig1_HTML.gif?as=webp
  tags:
      - Genome
      - Transcriptome
  extra-links:
    - type: pdf
      link: images/traeger_et_al_2015.pdf

- id: doi:10.1038/ncomms5817
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fncomms5817/MediaObjects/41467_2014_Article_BFncomms5817_Fig1_HTML.jpg?as=webp
  extra-links:
  - type: journal
    text: MSU Today
    link: http://msutoday.msu.edu/news/2014/a-single-evolutionary-road-may-lead-to-rome/
  tags:
      - Transcriptome
      - Genome
  extra-links:
    - type: pdf
      link: images/gallant_et_al_2014.pdf

- id: doi:10.1126/science.1254432
  image: images/best_eel_color_corrected_reduced.tif
  extra-links:
    - type: journal
      text: NPR
      link: http://www.npr.org/2014/06/26/325246710/a-shocking-fish-tale-surprises-evolutionary-biologists
    - type: journal
      link: http://www.wired.com/2014/06/electric-fish-convergent-evolution
      text: Wired
    - type: journal
      link: http://newswatch.nationalgeographic.com/2014/06/26/the-shocking-truth-about-electric-animals
      text: National Geographic
    - type: journal
      link: http://www.reuters.com/article/2014/06/26/us-science-fish-idUSKBN0F12UW20140626
      text: Reuters
    - type: journal
      link: http://msutoday.msu.edu/news/2014/sequencing-electric-eel-genome-unlocks-shocking-secrets/
      text: MSU Today
    - type: journal
      link: http://www.agenciasinc.es/Noticias/La-evolucion-de-los-peces-electricos-sorprende-a-los-cientificos
      text: CINA
    - type: pdf
      link: images/gallantetal2014.pdf

  tags:
      - Genome
      - Transcriptome
      - Evo-Devo

- id: doi:10.1016/j.celrep.2013.09.042
  image: images/S2211124713X00166_covhighres.jpg
  extra-links:
    - type: journal
      text: The Economist
      link: http://www.economist.com/news/science-and-technology/21588840-how-species-separate-still-mysterious-lepidoptera-make-things
    - type: journal
      text: LA Times
      link: http://www.latimes.com/science/sciencenow/la-sci-sn-butterflies-evolution-20131030,0,4630140.story#axzz2jKDjncAY)
    - type: journal
      text: Science Magazine
      link: http://news.sciencemag.org/biology/2013/10/scienceshot-butterfly-study-shows-genomes-change-bits-and-pieces-first)
    - type: pdf
      link: images/kronforstetal2013.pdf
  tags:
      - Genome
      - Transcriptome

- id: doi:10.3109/01677063.2013.799670
  image: https://www.tandfonline.com/na101/home/literatum/publisher/tandf/journals/content/ineg20/2013/ineg20.v027.i03/01677063.2013.799670/20150614/images/large/ineg_a_799670_f0006_b.jpeg
  tags:
    - Review
    - Evo-Devo
  extra-links:
    - type: pdf
      link: images/carlson_and_gallant_2013.pdf

- id: doi:10.1242/jeb.063222
  image: images/jeb063222f1.jpeg
  tags:
    - Evo-Devo
  extra-links:
    - type: pdf
      link: images/gallant_etal_2012.pdf

- id: doi:10.1007/s00359-011-0643-8
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1007%2Fs00359-011-0643-8/MediaObjects/359_2011_643_Fig5_HTML.gif?as=webp
  tags:
    - Signal Evolution
  extra-links:
    - type: pdf
      link: images/gallant_etal_2011.pdf
